apiVersion: v1
kind: Namespace
metadata:
  name: xkube 
  labels:
    env: prod
    team: devops
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: xkube-admin-config
  namespace: xkube
  labels:
    app: xkube-admin-config 
data:
  app.conf: |
    #
    appname = xkube
    httpport = 8080
    runmode = prod

    #mysql配置信息
    db_host = mysql_server 
    db_port = 3306
    db_user = root
    db_pass = xkube_DB_123456 
    db_name = db_xkube
    db_type = mysql

    #redis配置信息
    redisDb = "redis_server:6379"
    redisPasswd = "Redis_123456"

    ###前端模板配置
    template_type=front
    copyrequestbody = true
    TemplateLeft = "<<<" 
    TemplateRight = ">>>"

    ###登录session 配置
    SessionOn = true
    SessionName = "BsessionId"
    ServerName = "Bserver"
    SessionGCMaxLifetime = 7200
    SessionProvider = redis
    SessionProviderConfig = "redis_server:6379,100,Redis_123456"

    #admin用户名 此用户登录不用认证
    rbac_admin_user = admin
    #默认需要认证全部模块，添加排除认证的模块
    not_auth_package = public,index,task
    #默认认证类型 0 不认证 1 登录认证 2 实时认证
    user_auth_type = 1
    #登录地址
    rbac_auth_gateway = /public/login


    #登录日志记录
    securityLog = sec.log

    #是否启用手机验证码双重认证,需要true,不需要false,需配置阿里云验证码发送
    mobile_verify_code = false
    #阿里云短信验证码发送配置
    #AccessKey ID
    AliyunAkId = "LTAI5t7ySa6dsdfwSsAcnKxFw"
    #AccessKey Secret
    AliyunAkSecret = ""
    #签名名称
    SignName = "xkube助手"
    #模板CODE
    TemplateCode = "SMS_468230041"

    #用户最大登录失败次数
    max_login_fail_user = 5
    #用户IP最大登录失败次数
    max_login_fail_ip = 15
    #用户锁定时长,单位秒
    user_lock_time = 3600
    #IP锁定时长,单位秒
    ip_lock_time = 10800

    #wiki upload
    rootPath = /data/xkube
    uploadPath = static/upload
    domain = https://xkube-demo.eeenet.net

    #阿里云流水线回调的apikey,用于调用更新镜像的接口
    apiKey="dfw32dmoj324sdfsdffw342325r"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xkube-admin 
  namespace: xkube 
  labels:
    app: xkube-admin 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xkube-admin 
  template:
    metadata:
      labels:
        app: xkube-admin 
    spec:
      containers:
      - name: xkube-admin
        image: crpi-44hgz4440mgo9lnt.cn-guangzhou.personal.cr.aliyuncs.com/eeenet/xkube:3.7
        ports:
          - containerPort: 80
        volumeMounts:
          - mountPath: /app/conf
            name: config-volume
            readOnly: true
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /public/check
            port: 80
            scheme: HTTP
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /public/check
            port: 80
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 3
      volumes:
        - configMap:
            defaultMode: 420
            name: xkube-admin-config 
          name: config-volume
---
apiVersion: v1
kind: Service
metadata:
  name: xkube-admin 
  namespace: xkube 
  labels:
    app: xkube-admin 
spec:
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP 
  selector:
    app: xkube-admin 
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xkube-admin
  namespace: xkube 
spec:
  ingressClassName: nginx
  rules:
  - host: xkube.xxxx.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: xkube-admin
            port: 
              number: 80
