#
appname = xkube
httpport = 8080
runmode = prod

#mysql配置信息
db_host = mysql_server 
db_port = 3306
db_user = root
db_pass = xkube_DB_123456 
db_name = db_xkube
db_type = mysql

#redis配置信息
redisDb = "redis_server:6379"
redisPasswd = "Redis_123456"

###前端模板配置
template_type=front
copyrequestbody = true
TemplateLeft = "<<<" 
TemplateRight = ">>>"

###登录session 配置
SessionOn = true
SessionName = "BsessionId"
ServerName = "Bserver"
SessionGCMaxLifetime = 7200
SessionProvider = redis
SessionProviderConfig = "redis_server:6379,100,Redis_123456"

#admin用户名 此用户登录不用认证
rbac_admin_user = admin
#默认需要认证全部模块，添加排除认证的模块
not_auth_package = public,index,task
#默认认证类型 0 不认证 1 登录认证 2 实时认证
user_auth_type = 1
#登录地址
rbac_auth_gateway = /public/login


#登录日志记录
securityLog = sec.log

#是否启用手机验证码双重认证,需要true,不需要false,需配置阿里云验证码发送
mobile_verify_code = false
#阿里云短信验证码发送配置
#AccessKey ID
AliyunAkId = "LTAI5t7ySa6dsdfwxsgwsgsde"
#AccessKey Secret
AliyunAkSecret = ""
#签名名称
SignName = "xkube助手"
#模板CODE
TemplateCode = "SMS_468230041"

#用户最大登录失败次数
max_login_fail_user = 5
#用户IP最大登录失败次数
max_login_fail_ip = 15
#用户锁定时长,单位秒
user_lock_time = 3600
#IP锁定时长,单位秒
ip_lock_time = 10800

#wiki upload
rootPath = /data/xkube
uploadPath = static/upload
domain = https://xkube-demo.eeenet.net

#阿里云流水线回调的apikey,用于调用更新镜像的接口
apiKey="xe3f2dmoj32423sdfw23fdsfw34"
