apiVersion: v1
kind: Namespace
metadata:
  name: mrboard

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mrboard-config
  namespace: mrboard
data:
  app.conf: |
    #
    appname = mrboard
    httpport = 8080
    runmode = prod

    #mysql配置信息
    db_host = mysql.xkube.svc.cluster.local
    db_port = 3306
    db_user = root
    db_pass = xkube_DB_123456
    db_name = db_xkube
    db_type = mysql

    #redis配置信息
    redisDb = "redis.xkube.svc.cluster.local:6379"
    redisPasswd = "Redis_123456"

    ###前端模板配置
    template_type=front
    copyrequestbody = true
    TemplateLeft = "<<<"
    TemplateRight = ">>>"

    ###登录session 配置
    SessionOn = true
    SessionName = "BsessionId"
    ServerName = "Bserver"
    SessionGCMaxLifetime = 7200
    SessionProvider = redis
    SessionProviderConfig = "redis.xkube.svc.cluster.local:6379,100,Redis_123456"

    #admin用户名 此用户登录不用认证
    rbac_admin_user = admin
    #默认需要认证全部模块，添加排除认证的模块
    not_auth_package = public,index,task
    #默认认证类型 0 不认证 1 登录认证 2 实时认证
    user_auth_type = 1
    #登录地址
    rbac_auth_gateway = /public/login

    #登录日志记录
    securityLog = sec.log

    #是否启用手机验证码双重认证,需要true,不需要false
    mobile_verify_code = false

    #用户最大登录失败次数
    max_login_fail_user = 5
    #用户IP最大登录失败次数
    max_login_fail_ip = 15
    #用户锁定时长,单位秒
    user_lock_time = 3600
    #IP锁定时长,单位秒
    ip_lock_time = 10800

    #wiki upload
    rootPath = /app
    uploadPath = static/upload
    domain = https://mrboard.xx-xx.xyz

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mrboard
  namespace: mrboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mrboard
  template:
    metadata:
      labels:
        app: mrboard
    spec:
      containers:
        - name: mrboard
          image: mrboard:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /app/conf/app.conf
              subPath: app.conf
          readinessProbe:
            httpGet:
              path: /public/check
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /public/check
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: config
          configMap:
            name: mrboard-config

---
apiVersion: v1
kind: Service
metadata:
  name: mrboard
  namespace: mrboard
spec:
  selector:
    app: mrboard
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mrboard
  namespace: mrboard
spec:
  ingressClassName: nginx
  rules:
    - host: mrboard.xx-xx.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mrboard
                port:
                  number: 8080
