apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: xkube-backend
  namespace: mrboard
  labels:
    app: xkube
    release: prometheus
spec:
  selector:
    matchLabels:
      app: xkube-backend
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - mrboard
